version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongoDB
    restart: always
    env_file:
      - ./app.env

    ports:
      - '27017:27017'

  redis:
    image: redis
    container_name: redisDB
    ports:
      - '6379:6379'
volumes:
  mongodb:
  redisDB:

